//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buscadro_de_RUCs.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Buscadro_de_RUCs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44089
        ///0100001825001
        ///0100004993001
        ///0100012772001
        ///0100014091001
        ///0100030345001
        ///0100030923001
        ///0100040336001
        ///0100041060001
        ///0100045590001
        ///0100050376001
        ///0100052851001
        ///0100054287001
        ///0100055474001
        ///0100058163001
        ///0100058601001
        ///0100066422001
        ///0100070622001
        ///0100073204001
        ///0100075746001
        ///0100085513001
        ///0100093814001
        ///0100103654001
        ///0100122274001
        ///0100125103001
        ///0100135169001
        ///0100151810001
        ///0100152396001
        ///0100159847001
        ///0100172774001
        ///0100173780001
        ///0100177906001
        ///0100184225001
        ///0100192301001
        ///0100194901 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string AR {
            get {
                return ResourceManager.GetString("AR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 43606
        ///0100132109001
        ///0100428085001
        ///0100732957001
        ///0101053361001
        ///0101177889001
        ///0101221018001
        ///0101289445001
        ///0101518660001
        ///0101695575001
        ///0101962090001
        ///0102042397001
        ///0102063955001
        ///0102087798001
        ///0102119831001
        ///0102133998001
        ///0102191590001
        ///0102333390001
        ///0102346640001
        ///0102402518001
        ///0102532066001
        ///0102604428001
        ///0102637774001
        ///0102647203001
        ///0102721032001
        ///0102876901001
        ///0103076451001
        ///0103554580001
        ///0104673520001
        ///0160000190001
        ///0160000270001
        ///0160000430001
        ///0160000510001
        ///0160000780001
        ///0160000860 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string CE {
            get {
                return ResourceManager.GetString("CE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_38005243_stock_illustration_vector_magnifying_glass {
            get {
                object obj = ResourceManager.GetObject("depositphotos_38005243-stock-illustration-vector-magnifying-glass", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DFWEOWHCQZAMRNH7ALRFQYVPTU {
            get {
                object obj = ResourceManager.GetObject("DFWEOWHCQZAMRNH7ALRFQYVPTU", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44090
        ///0100021880001
        ///0100720622001
        ///0100875160001
        ///0101405314001
        ///0101732634001
        ///0102284924001
        ///0190000435001
        ///0190004937001
        ///0190005070001
        ///0190008886001
        ///0190020304001
        ///0190057895001
        ///0190131947001
        ///0190147983001
        ///0190152227001
        ///0190153797001
        ///0190154351001
        ///0190155617001
        ///0190345777001
        ///0190361810001
        ///0190382486001
        ///0190448169001
        ///0190460266001
        ///0200409043001
        ///0201179512001
        ///0201550654001
        ///0291505511001
        ///0301256996001
        ///0400381109001
        ///0400441291001
        ///0400960878001
        ///0401233481001
        ///0401682216001
        ///0490054529 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string EX {
            get {
                return ResourceManager.GetString("EX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44095
        ///0104841614001
        ///0105375091001
        ///0190378438001
        ///0190390977001
        ///0300823481001
        ///0301230728001
        ///0301251468001
        ///0301556361001
        ///0391015023001
        ///0400089215001
        ///0591720872001
        ///0600762173001
        ///0603912627001
        ///0700212434001
        ///0700324072001
        ///0700507361001
        ///0700638208001
        ///0701820953001
        ///0701935223001
        ///0701949018001
        ///0701957490001
        ///0702227372001
        ///0702417833001
        ///0702439969001
        ///0702467705001
        ///0702522228001
        ///0702721747001
        ///0702881137001
        ///0703006882001
        ///0703052571001
        ///0703133694001
        ///0703165159001
        ///0703249664001
        ///0703254656 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string FA {
            get {
                return ResourceManager.GetString("FA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 43900
        ///0190001490001
        ///0190003701001
        ///0190005070001
        ///0190005232001
        ///0190006247001
        ///0190007510001
        ///0190021831001
        ///0190050033001
        ///0190055965001
        ///0190057127001
        ///0190061264001
        ///0190062317001
        ///0190066304001
        ///0190072002001
        ///0190099725001
        ///0190104567001
        ///0190110001001
        ///0190115151001
        ///0190122271001
        ///0190123626001
        ///0190146677001
        ///0190150496001
        ///0190159663001
        ///0190167348001
        ///0190168018001
        ///0190168190001
        ///0190310647001
        ///0190316025001
        ///0190341992001
        ///0190347370001
        ///0190349594001
        ///0190365751001
        ///0190410617001
        ///0390011024 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string GC {
            get {
                return ResourceManager.GetString("GC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 44088
        ///0100001841001
        ///0100001908001
        ///0100002708001
        ///0100002732001
        ///0100003821001
        ///0100003938001
        ///0100004407001
        ///0100005123001
        ///0100005560001
        ///0100005669001
        ///0100006832001
        ///0100007269001
        ///0100007780001
        ///0100007863001
        ///0100008887001
        ///0100010362001
        ///0100011360001
        ///0100011709001
        ///0100011915001
        ///0100012103001
        ///0100012327001
        ///0100012582001
        ///0100014158001
        ///0100014901001
        ///0100015213001
        ///0100015387001
        ///0100015437001
        ///0100016112001
        ///0100017698001
        ///0100019942001
        ///0100020239001
        ///0100020643001
        ///0100021229001
        ///0100021344 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string ME {
            get {
                return ResourceManager.GetString("ME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vector_trash_icon_png_image_4152709 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vector-trash-icon-png-image_4152709", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap right_600x400_1 {
            get {
                object obj = ResourceManager.GetObject("right_600x400_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
